services:
  was-110-monitoring:
    build: .
    container_name: sfp_monitor
    restart: unless-stopped
    ports:
      - 5050:5050
    environment:
      - SFP_ROOT_PASSWORD
      - FETCH_INTERVAL_SECONDS
    volumes:
      - ./static:/app/static
      - sfp_data_volume:/data
volumes:
  sfp_data_volume: null
